#
# (C) 2021 Renesas Electronics
#

# FIXME: "Source" data units not in the VSS standard catalog will eventually 
# be stored here to avoid polluting VSS with units from everything it might be
# interfaced with.

what units were missing:
ms -added
m/s - added
unix time in ms but actually covered by ms unit, i.e. ms is unit rather than some unix time unit varient

actually missing:
mph

Unusual abstract:
arg.geometry.TrafficInfo.SegmentLane
arg.geometry.TrafficInfo.Intersection
